import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Crypto App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/prism.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Made by Drogaz#6521
          </p>
        </div>

        <div className={styles.center}>
          <h1 className={inter.className}>Crypto Prism</h1>
          <div className={styles.thirteen}>
            <Image
              src="/prism.png"
              alt="13"
              width={80}
              height={60}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="/Data"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Prices <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
                See the latest prices of the top 100 cryptocurrencies.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Charts <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            See the latest trends in the crypto market with&nbsp;charts.
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Buy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
                Buy cryptocurrencies with&nbsp;your&nbsp;credit card.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              API <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
                Use our API to get the latest prices and trends.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
